// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOi3ATxvvEcZ_G9IN7xJOVfAy77_4bhQ',
    appId: '1:137255433970:web:e1fb64c00228e4c49b826b',
    messagingSenderId: '137255433970',
    projectId: 'fluttabd',
    authDomain: 'fluttabd.firebaseapp.com',
    storageBucket: 'fluttabd.firebasestorage.app',
    measurementId: 'G-PS8VLY759Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0wIj0-dnSTjT9IGR9lcTclSRDgBgdOQM',
    appId: '1:137255433970:android:1ff381f1f617660e9b826b',
    messagingSenderId: '137255433970',
    projectId: 'fluttabd',
    storageBucket: 'fluttabd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADj14cwc2i-INbURt61FiVHhruySwg7jU',
    appId: '1:137255433970:ios:dfb55f41bb2eef879b826b',
    messagingSenderId: '137255433970',
    projectId: 'fluttabd',
    storageBucket: 'fluttabd.firebasestorage.app',
    iosBundleId: 'com.example.fluttabd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADj14cwc2i-INbURt61FiVHhruySwg7jU',
    appId: '1:137255433970:ios:dfb55f41bb2eef879b826b',
    messagingSenderId: '137255433970',
    projectId: 'fluttabd',
    storageBucket: 'fluttabd.firebasestorage.app',
    iosBundleId: 'com.example.fluttabd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQOi3ATxvvEcZ_G9IN7xJOVfAy77_4bhQ',
    appId: '1:137255433970:web:c834ff724d28c23f9b826b',
    messagingSenderId: '137255433970',
    projectId: 'fluttabd',
    authDomain: 'fluttabd.firebaseapp.com',
    storageBucket: 'fluttabd.firebasestorage.app',
    measurementId: 'G-RRL34RJL5V',
  );
}
